'use strict'

const TokenType = Object.freeze({
  EOF: 'EOF',
  IDENTIFIER: 'IDENTIFIER',
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  TEMPLATE: 'TEMPLATE',

  BUEK: 'BUEK',
  TAPEK: 'TAPEK',
  CETAK: 'CETAK',
  JIKO: 'JIKO',
  LAIN: 'LAIN',
  SALAMO: 'SALAMO',
  UNTUAK: 'UNTUAK',
  KARAJO: 'KARAJO',
  BALIAKAN: 'BALIAKAN',
  BATUA: 'BATUA',
  SALAH: 'SALAH',
  JO: 'JO',
  ATAU: 'ATAU',
  INDAK: 'INDAK',
  KOSONG: 'KOSONG',
  DATANTU: 'DATANTU',
  BARANTI: 'BARANTI',
  LANJUIK: 'LANJUIK',

  PLUS: 'PLUS',
  MINUS: 'MINUS',
  STAR: 'STAR',
  SLASH: 'SLASH',
  PERCENT: 'PERCENT',
  EQ: 'EQ',
  NEQ: 'NEQ',
  LT: 'LT',
  GT: 'GT',
  LTE: 'LTE',
  GTE: 'GTE',
  ASSIGN: 'ASSIGN',
  PLUS_ASSIGN: 'PLUS_ASSIGN',
  MINUS_ASSIGN: 'MINUS_ASSIGN',
  STAR_ASSIGN: 'STAR_ASSIGN',
  SLASH_ASSIGN: 'SLASH_ASSIGN',
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  LPAREN: 'LPAREN',
  RPAREN: 'RPAREN',
  LBRACE: 'LBRACE',
  RBRACE: 'RBRACE',
  DOT: 'DOT',
  COMMA: 'COMMA',
  SEMICOLON: 'SEMICOLON'
})

const KEYWORDS = Object.freeze({
  buek: TokenType.BUEK,
  tapek: TokenType.TAPEK,
  cetak: TokenType.CETAK,
  jiko: TokenType.JIKO,
  lain: TokenType.LAIN,
  salamo: TokenType.SALAMO,
  untuak: TokenType.UNTUAK,
  karajo: TokenType.KARAJO,
  baliakan: TokenType.BALIAKAN,
  batua: TokenType.BATUA,
  salah: TokenType.SALAH,
  jo: TokenType.JO,
  atau: TokenType.ATAU,
  indak: TokenType.INDAK,
  kosong: TokenType.KOSONG,
  datantu: TokenType.DATANTU,
  baranti: TokenType.BARANTI,
  lanjuik: TokenType.LANJUIK
})

module.exports = { KEYWORDS, TokenType }
